config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root 'places#index'
    resources :places do
      resources :comments, only: :create #allows posting to the comments controller and allows us to pass through a place_id, which we will use on our comments form.
      resources :photos, only: :create #allows posting to the photos controller and allows us to pass through a place id.
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :place
    after_create :send_comment_email #sends automated email after comment has been created
    
    RATINGS = {
     'one star': '1_star',
     'two stars': '2_stars',
     'three stars': '3_stars',
     'four stars': '4_stars',
     'five stars': '5_stars'
    }  #for a rating system in the comments section
    
    def humanized_rating
        RATINGS.invert[self.rating]
    end
    #allow us to call a humanized_rating from every single comment we look up.


    def send_comment_email #active callback - automatically send outs e-mail when a user puts in a comment
        NotificationMailer.comment_added(self).deliver
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :place #a photo belongs to a place
    mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :user #a place belongs to a user
    has_many :comments #a place can have many comments
    has_many :photos #a place can have many photos
    
    
    geocoded_by :address
    after_validation :geocode
    
    validates :name, length: {minimum: 3}, presence: true#validate name field has minimum of 3 char
    validates :address, presence: true #validate presence of address
   
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :places #a user can create many places
  has_many :comments #a user can create many comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user! #authenticate user before any comments are logged in
    
    def create
        @place = Place.find(params[:place_id]) #finds the place associated with the id
        @place.comments.create(comment_params.merge(user: current_user)) #create comment that's connected to the place that's loaded
        #merge method - combines two dictionaries (dictionary is a data structure known as a hash table)
        redirect_to place_path(@place) #sends user back to place page after user creates the item
    end
    
    private
    
    def comment_params #pull data out of the comments
        params.require(:comment).permit(:message, :rating)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :authenticate_user! #authenticate the user before any photos are added
    
    def create #save new photos into database
        @place = Place.find(params[:place_id]) #load the place that the photo belongs too
        @place.photos.create(photo_params)
        redirect_to place_path(@place) #redirect user to place once image is done uploading
    end
    
    private
    
    def photo_params #pulls the picture values out of the form
        params.require(:photo).permit(:caption, :picture)
    end
    
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def index
        @places = Place.order(:name).page params[:page]
    end
    
    def new
        @place = Place.new
    end

    def create
        @place = current_user.places.create(place_params)
        if @place.valid?
        redirect_to root_path
        else
        render :new, status: :unprocessable_entity
        end
    end
    
    def show
        @place = Place.find(params[:id])
        @comment = Comment.new
        @photo = Photo.new
    end
    
    def edit
        @place = Place.find(params[:id])
        
        if @place.user != current_user
            return render text: 'Not Allowed', status: :forbidden
        end
    end
    
    def update
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render text: 'Not Allowed', status: :forbidden
        end
        @place.update_attributes(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        @place = Place.find(params[:id])
        if @place.user != current_user
          return render text: 'Not Allowed', status: :forbidden
        end
        
        @place.destroy
        redirect_to root_path
    end
    
    private
    
    def place_params
        params.require(:place).permit(:name, :description, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show #adding show action to the controller
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Don't Pho-get it!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <%= link_to 'The Pho Finder', root_path, class: 'navbar-brand' %>
      
     <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to new_place_path, class: 'nav-link' do %>
        <i class="fa fa-plus-circle"></i>
        New Place
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Edit Your Place</h1>
<%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'pho_carousel.jpg' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'pho_carousel2.jpg' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'pho_carousel3.jpg' %>
    </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h1><% @places.each do |place| %></h1>
<div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />
    
    <% if place.user.present? %>
    <small><%= place.user.email %></small>
    <% end %>
    
     <!-- will run code below if a comment exists -->
    
    <% if place.comments.present? %>
    <div class="col-12">
         <blockquote>
             <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b>
            <% end %>
             <%= place.comments.last.message %>
            <small><%= place.comments.last.user.email %></small>
         </blockquote>
     </div>
    <% end  %>
</div>
<% end %>

<!-- Code above will display the last comment of each place on the home page -->

<%= paginate @places%>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Enter Your Place Details</h1>
<%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
    <h1><%= @place.name %></h1>
    <i><%= @place.address %></i>
    <br/><br/>
    <p><%= @place.description %></p>
    
    <% if @place.latitude.present? && @place.longitude.present? %>
    
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDd9HxrvdyB39eswkH3slc8cMmTdwN1rn0&callback=initMap">
    </script>
    
        <div id="map"></div>
    <% end %>
    
    
    <br />
    
    <div class="float-right">
    <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
    <% end %>
    </div>
    </div>

<div class="clear"></div>

<!-- Modal Comment -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Add a comment</h5>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
      <div class="modal-body">
            <%= f.input :message %>
            <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
            </div>
            <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
        <% end %>
        </div>
      </div>
    </div>
    
<% if false %>
Above code creates a message and rating field within the modal.
<% end %>

 
 <div class="col-10 offset-1">
 <h1 class="float-left">Comments & User Photos</h1>
 
 
 <!-- Button trigger comments modal -->
 <button type="button" class="btn btn-primary btn-md float-right" data-toggle="modal" data-target="#exampleModal">
     Add a comment
 </button>
 </div>
 
 <div class="clear"></div>
 
 <!-- End button trigger comments modal -->
 
     <!-- Modal Photos -->

    <div class="modal fade" id="PhotoModal" tabindex="-1" role="dialog" aria-labelledby="PhotoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="PhotoModalLabel">Add a photo</h5>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
      <div class="modal-body">
            <%= f.input :picture %>
            <%= f.input :caption %>
            </div>
            
            <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add a Photo", class: 'btn btn-info' %>
        </div>
        <% end %>
        </div>
      </div>
    </div>

    <!-- End Modal Photos -->

    <!-- Photos butto modal -->
    <div class="col-10 offset-1">
    <button type="button" class="btn btn-info btn-lg float-right" data-toggle="modal" data-target="#PhotoModal">
     Add a Photo
     
     <!-- You have to change the data target to match the id ("Photo Modal") for it to display the proper fields -->

 </button>
 </div>
 
 <div class="clear"></div>
 
    <!-- End Photos button modal -->
    
    <!-- User photo uploads -->
    <div class="container-fluid">
        <div class="row">
            <div class = "rounded mx-auto d-block">
    <% @place.photos.each do |photo| %>
    <figure>
     <%= image_tag photo.picture, class:'image-sizing' %>
  <figcaption class="figure-caption text-center"><%= photo.caption %></figcaption>
<% end %>
</figure>
</div>
</div>
</div>
    <!-- End user photo uploads -->
 
 <div class="row">
 <% @place.comments.each do |comment| %>
 <div class="col-12 col-sm-6">
         <blockquote>
             <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b>
            <% end %>
             <%= comment.message %>
            <small><%= comment.user.email %></small>
         </blockquote>
     </div>
     <% end %>
    </div> 
    
    <!-- End Modal Comments -->
    
    
<% if false %>
This code will use a loop to grab all the comments from the database and show them on the places page along with the rating, message and email address of the user who created it.
"humanized_rating" shows the rating along with the comment.
<% end %>

app/views/users/show.html.erb
<div class="booyah-box">
    <div class="row">
        <div class="col-4">
    <%= image_tag 'user_icon.png' %>
    </div>
    
    <div class="col-8">
    <h1><%= @user.email %></h1>
    <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
    <h4><%= @user.comments.count %> total comments</h4>
    <h4><%= @user.comments.count %> total reviews</h4>
    <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
    </div>
    <div class="clear"></div>
</div>

<br /><br />
<h1 class="text-center">My Comments</h1>
<br /><br />
<div class = "row">
<% @user.comments.each do |comment| %>
     <div class="col-12 col-sm-6">
         <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
         <blockquote>
             <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b>
            <% end %>
             <%= comment.message %>
            <small><%= comment.user.email %></small>
         </blockquote>
     </div>
<% end %>

<% if false %>
Above code is to clean up user interface in the comments section
<% end %>
</div>

<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />

<% @user.places.each do |place| %>

<div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />
    
    <% if place.user.present? %> <!-- will run code below if a comment exists -->
    <small><%= place.user.email %></small>
    <% end %>
    
    <% if place.comments.present? %>
    <div class="col-12">
         <blockquote>
             <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b>
            <% end %>
             <%= place.comments.last.message %>
            <small><%= place.comments.last.user.email %></small>
         </blockquote>
     </div>
    <% end  %>
</div>
<% end %>